-- Channel calendar sync — import Airbnb / Booking.com iCal feeds so a booking on any channel
-- blocks those dates on caonabo35.com (prevents double-bookings). Applied to prod 2026-07-15 via MCP.

create table if not exists public.channel_calendars (
  id          bigint generated by default as identity primary key,
  room_id     text references public.rooms(id) on delete cascade,   -- null = all rooms (whole-property listing)
  label       text,
  source      text default 'airbnb',                                 -- airbnb | booking | other
  ics_url     text not null,
  active      boolean not null default true,
  last_synced timestamptz,
  last_status text,
  created_at  timestamptz not null default now()
);
alter table public.channel_calendars enable row level security;
drop policy if exists "channel_calendars admin" on public.channel_calendars;
create policy "channel_calendars admin" on public.channel_calendars for all to authenticated using (true) with check (true);

create table if not exists public.channel_blocks (
  room_id   text not null,
  date      date not null,
  source    text not null default 'airbnb',
  label     text,
  synced_at timestamptz not null default now(),
  primary key (room_id, date, source)
);
create index if not exists channel_blocks_date_idx on public.channel_blocks(date);
alter table public.channel_blocks enable row level security;
drop policy if exists "channel_blocks read"  on public.channel_blocks;
create policy "channel_blocks read"  on public.channel_blocks for select using (true);
drop policy if exists "channel_blocks write" on public.channel_blocks;
create policy "channel_blocks write" on public.channel_blocks for all to authenticated using (true) with check (true);
