-- Caonabo 35 — security hardening + multicalendar foundation.
-- Run ONCE, top to bottom, in the Supabase dashboard → SQL Editor → New query → Run.
-- Idempotent (safe to re-run). Pairs with the code changes on branch fix/security-persistence-multicalendar.
--
-- ⚠️  ALSO REQUIRED (dashboard, 20 seconds): Authentication → Providers → Email → turn OFF "Enable Signups".
--     The admin panel writes to the DB as an authenticated user; with signups open, anyone could register a
--     throwaway account and get the same write access. There is no guest-signup feature, so disabling it is safe.

-- ── 1) SECURITY: public visitors may only CREATE bookings as pending + unpaid ─────────────────────────────
--     (was `with check (true)` — anyone could insert a fake "confirmed & paid" booking and block real guests)
drop policy if exists "Public can insert bookings" on public.bookings;
create policy "Public can insert bookings" on public.bookings
  for insert to anon, authenticated
  with check (status = 'pending' and coalesce(paid, false) = false);

-- ── 2) MULTICALENDAR: per-night price + availability per room (the Airbnb grid needs a (room,date) grain) ──
-- NOTE: rooms.id is TEXT in the live DB (values '1'..'7' plus legacy '201'..'208'),
-- so room_id is text to match the FK. Applied to production 2026-07-15 via MCP.
create table if not exists public.room_nights (
  room_id    text not null references public.rooms(id) on delete cascade,
  date       date not null,
  price      numeric,               -- null = inherit the room's base/override price
  available  boolean not null default true,
  min_nights int,
  note       text,
  updated_at timestamptz not null default now(),
  primary key (room_id, date)
);
create index if not exists room_nights_date_idx on public.room_nights(date);
alter table public.room_nights enable row level security;
drop policy if exists "room_nights read"        on public.room_nights;
create policy "room_nights read"        on public.room_nights for select using (true);
drop policy if exists "room_nights admin write" on public.room_nights;
create policy "room_nights admin write" on public.room_nights for all to authenticated using (true) with check (true);

-- ── 3) REVIEWS: so admin publish/hide/delete actually persists (was in-memory only) ───────────────────────
create table if not exists public.reviews (
  id         bigint generated by default as identity primary key,
  name       text,
  rating     int,
  body       text,
  approved   boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.reviews enable row level security;
drop policy if exists "reviews public read approved" on public.reviews;
create policy "reviews public read approved" on public.reviews for select using (approved = true);
drop policy if exists "reviews admin all"           on public.reviews;
create policy "reviews admin all"           on public.reviews for all to authenticated using (true) with check (true);

-- ── 4) SETTINGS: columns the app writes but the schema was missing (hero subtitle + seasonal pricing) ──────
alter table public.settings add column if not exists hero_subtitle text;
alter table public.settings add column if not exists seasons_json  text;

-- ── 5) DISCOUNTS: the promo-code table the app expects ────────────────────────────────────────────────────
create table if not exists public.discounts (
  id         bigint generated by default as identity primary key,
  code       text unique,
  label      text,
  type       text default 'percent',
  value      numeric,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.discounts enable row level security;
drop policy if exists "discounts read"      on public.discounts;
create policy "discounts read"      on public.discounts for select using (true);
drop policy if exists "discounts admin all" on public.discounts;
create policy "discounts admin all" on public.discounts for all to authenticated using (true) with check (true);
